/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Facade;

import Main.Window;
import Snail.Main;
import Snake.JuegoSnake;

/**
 *
 * @author KelvinOjeda
 */

public class FacadeAccess extends javax.swing.JFrame {

    /**
     * Creates new form FacadeAccess
     */
    Window asteroidGame;
    Main snailGame;
    JuegoSnake snakeGame;
    public FacadeAccess() {
        initComponents();
        this.asteroidGame= new Window();
        this.snailGame= new Main();
        this.snakeGame= new JuegoSnake();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBAsteroid = new javax.swing.JButton();
        jBTetris = new javax.swing.JButton();
        jBSnail = new javax.swing.JButton();
        jBSnake = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBAsteroid.setText("Asteroid Game");
        jBAsteroid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAsteroidActionPerformed(evt);
            }
        });

        jBTetris.setText("Tetris Game");

        jBSnail.setText("Snail Game");
        jBSnail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSnailActionPerformed(evt);
            }
        });

        jBSnake.setText("Snake Game");
        jBSnake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSnakeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jBAsteroid)
                .addGap(67, 67, 67)
                .addComponent(jBSnail)
                .addGap(55, 55, 55)
                .addComponent(jBTetris)
                .addGap(61, 61, 61)
                .addComponent(jBSnake)
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBAsteroid)
                    .addComponent(jBTetris)
                    .addComponent(jBSnail)
                    .addComponent(jBSnake))
                .addContainerGap(238, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBAsteroidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAsteroidActionPerformed
       this.asteroidGame.setVisible(true);
    }//GEN-LAST:event_jBAsteroidActionPerformed

    private void jBSnailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSnailActionPerformed
        //this.snailGame.setVisible(true);
    }//GEN-LAST:event_jBSnailActionPerformed

    private void jBSnakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSnakeActionPerformed
        //this.snakeGame.setVisible(true);
    }//GEN-LAST:event_jBSnakeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FacadeAccess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FacadeAccess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FacadeAccess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FacadeAccess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FacadeAccess().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAsteroid;
    private javax.swing.JButton jBSnail;
    private javax.swing.JButton jBSnake;
    private javax.swing.JButton jBTetris;
    // End of variables declaration//GEN-END:variables
}
